### ISSUE TITLE
Configure on AppVeyor

### ISSUE THREAD

**Issue by Ventajou** [Ventajou/WPInfo#9]
AppVeyor is free for open source projects, let's leverage it to build WPInfo.

**Comment by DavidRawling** [comment]
Sounds like a good idea.

I've registered with my Github account / OAuth, and granted it access to WPinfo. Ventajou - you might want to see if you can see my config there for the project. If not, perhaps you should set it up as the owner of the project (or perhaps we find a way to share it on AppVeyor).

**Comment by Ventajou** [comment]
Added you to my project!
